name: Deploy Internal Ingress-Nginx

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment (prod or stg or qa)'
        required: true
        type: choice
        options:
          - prod
          - stg
          - qa

jobs:
  deploy:
    name: Deploy Internal Ingress
    runs-on: ubuntu-latest

    environment: ${{ inputs.environment }}
#cluster and rg name is started with mycluster
    env:
      CLUSTER_NAME: mycluster-${{ inputs.environment }}-aks
      RESOURCE_GROUP: mycluster-${{ inputs.environment }}-apps-rg
      ENV: ${{ inputs.environment }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install kubectl
        uses: azure/setup-kubectl@v4

      - name: Set AKS context
        uses: azure/aks-set-context@v4
        with:
          resource-group: ${{ env.RESOURCE_GROUP }}
          cluster-name: ${{ env.CLUSTER_NAME }}

      - name: Setup Helm
        uses: azure/setup-helm@v4.3.0

      - name: Add Helm repo
        run: |
          helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
          helm repo update

      - name: Deploy Internal Ingress
        run: |
          helm upgrade --install ingress-nginx-internal ingress-nginx/ingress-nginx \
            --namespace ingress-nginx \
            --create-namespace \
            -f ingress-nginx-internal/${ENV}/values.yaml
